import type { Metadata } from "next";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Separator } from "@/components/ui/separator";
import { SearchDialog } from "@/components/ui/search-dialog";
import { ThemeSwitcher } from "@/components/ui/theme-switcher";
import { cn } from "@/lib/utils";
import { AccountMenu } from "@/components/ui/account-menu";

export const users = [
  {
    id: "1",
    name: "Arham Khan",
    username: "Aarhamkhnz",
    email: "hello@arhamkhnz.com",
    avatar: "/avatars/arhamkhnz.png",
    role: "administrator",
  },
  // {
  //   id: "2",
  //   name: "Ammar Khan",
  //   username: "ammarkhnz",
  //   email: "hello@ammarkhnz.com",
  //   avatar: "",
  //   role: "admin",
  // },
];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const contentLayout = "centered"; // This can be dynamic based on your app's state or props  "centered" | "full-width"

  return (
    <SidebarProvider>
      <AppSidebar  />
      <SidebarInset
        className={cn(
          contentLayout === "centered" && "!mx-auto max-w-screen-2xl",
          // Adds right margin for inset sidebar in centered layout up to 113rem.
          // On wider screens with collapsed sidebar, removes margin and sets margin auto for alignment.
          "max-[113rem]:peer-data-[variant=inset]:!mr-2 min-[101rem]:peer-data-[variant=inset]:peer-data-[state=collapsed]:!mr-auto p-2 bg-card",
        )}
      >
        <div className=" rounded-2xl bg-background h-[97vh] flex flex-col">
          <header className="flex h-12 shrink-0 items-center gap-2 border-b transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12 w-full">
          <div className="flex w-full items-center justify-between px-4 lg:px-6">
            <div className="flex items-center gap-1 lg:gap-2">
              <SidebarTrigger className="-ml-1" />
              <Separator orientation="vertical" className="mx-2 data-[orientation=vertical]:h-4" />
              <SearchDialog />
            </div>
            <div className="flex items-center gap-2">
              <ThemeSwitcher />
              <AccountMenu users={users} />
            </div>
          </div>
        </header>
        <div className="p-4 md:p-6 h-full">{children}</div>
        </div>
      </SidebarInset>
    </SidebarProvider>
  );
}
