import { BankAccountType, Department, Designation, EmploymentType, Gender, InviteStatus, MaritalStatus, Role, WorkLocation } from "@prisma/client";

// types

type DesignationName = 'CTO' | 'CFO' | 'CMO' | 'Software Engineer' | 'Junior Software Engineer' | 'HR Manager' | 'Sales Manager' | 'Marketing Manager' | 'Finance Manager' | 'Finance Manager' | 'Designer'

type DesignationData = { name: DesignationName, tenantId: string }


type DepartmentName = 'IT' | 'HR' | 'Sales' | 'Marketing' | 'Finance' | 'Engineering' | 'Legal'

type DepartmentData = {
    name: DepartmentName
    code: string
    description: string,
    tenantId: string,
    createdAt?: Date
}

type WorkLocationName = 'Head Office' | 'Regional Office' | 'Branch Office' | 'Sales Office' | 'Marketing Office' | 'Finance Office' | 'Legal Office' | 'R&D Center' | 'Support Office'

type WorkLocationData = {
    name: WorkLocationName
    state: string
    city: string
    pincode: string
    tenantId: string,
    addressLine1: string
    addressLine2: string
}



const businessId = 'c5e7f0a4-3b3b-4b6b-8b4b-2b4b4b4b4b4b'
const userId = 'c5e7f0a4-3b3b-4b6b-8b4b-6b4b3b3b3b3b'
export const businessData = {
    id: businessId,
    name: 'Horizontal Pvt Ltd',
    subdomain: 'horizontal',
    email: 'test@example.com',
    password: '12345678',
}
export const userData = {
    id: userId,
    name: 'John Doe',
    email: 'test@example.com',
    password: '12345678',
}

// utils

function getDateMonthsAgo(monthsAgo: number) {
    const date = new Date();
    date.setMonth(date.getMonth() - monthsAgo);
    return date;
}

export const getDesignationId = (name: DesignationName, designations: Designation[]) => {
    const found = designations.find(d => d.name === name)
    if (!found) {
        return '12345678-1234-1234-1234-123456789012'
    }
    return found.id
}

export const getDepartmentId = (name: DepartmentName, departments: Department[]) => {
    const found = departments.find(d => d.name === name)
    if (!found) {
        return '12345678-1234-1234-1234-123456789012'
    }
    return found.id
}

export const getWorkLocationId = (name: WorkLocationName, workLocations: WorkLocation[]) => {
    const found = workLocations.find(d => d.name === name)
    if (!found) {
        return '12345678-1234-1234-1234-123456789012'
    }
    return found.id
}

export const getEmployeesData = (designations: Designation[], departments: Department[], workLocations: WorkLocation[]) => {

    return [
        {
            bankAccountHolderName: "Alice",
            bankAccountNumber: "1111111111",
            bankAccountType: BankAccountType.SAVINGS,
            bankName: "Demo Bank",
            bankBranch: "Main Branch",
            bankIfscCode: "DEMO1234",
            aadhaarNumber: "111111111111",
            panNumber: "ABCDE1111F",
            driverLicenseNumber: "DL1111111",
            inviteUser: true,
            role: Role.MANAGER,
            workLocation: getWorkLocationId("Head Office", workLocations),
            department: getDepartmentId("Sales", departments),
            designation: getDesignationId("Sales Manager", designations),
            tenantId: businessId,
            dateOfBirth: new Date("1990-01-01"),
            dateOfJoining: new Date("2020-01-01"),
            reportingManagerId: null,
            language: "English",
            nationality: "INDIA",
            email: "alice@example.com",
            phoneNumber: "9000000001",
            workEmail: "alice@example.com",
            addressLine1: "123 Main St",
            addressLine2: "Suite 100",
            name: "Alice",
            employmentType: EmploymentType.FULL_TIME,
            gender: Gender.FEMALE,
            maritalStatus: MaritalStatus.SINGLE,
        },
        {
            bankAccountHolderName: "Bob",
            bankAccountNumber: "2222222222",
            bankAccountType: BankAccountType.SAVINGS,
            bankName: "Demo Bank",
            bankBranch: "Main Branch",
            bankIfscCode: "DEMO1234",
            aadhaarNumber: "222222222222",
            panNumber: "ABCDE2222F",
            driverLicenseNumber: "DL2222222",
            inviteUser: true,
            role: Role.EMPLOYEE,
            workLocation: getWorkLocationId("Head Office", workLocations),
            department: getDepartmentId("Engineering", departments),
            designation: getDesignationId("Software Engineer", designations),
            tenantId: businessId,
            dateOfBirth: new Date("1991-01-01"),
            dateOfJoining: new Date("2021-01-01"),
            reportingManagerId: null,
            language: "English",
            nationality: "INDIA",
            email: "bob@example.com",
            phoneNumber: "9000000002",
            workEmail: "bob@example.com",
            addressLine1: "456 Side St",
            addressLine2: "Floor 2",
            name: "Bob",
            employmentType: EmploymentType.FULL_TIME,
            gender: Gender.MALE,
            maritalStatus: MaritalStatus.MARRIED,
        },
        {
            bankAccountHolderName: "Dave",
            bankAccountNumber: "3333333333",
            bankAccountType: BankAccountType.SAVINGS,
            bankName: "Demo Bank",
            bankBranch: "Main Branch",
            bankIfscCode: "DEMO1234",
            aadhaarNumber: "333333333333",
            panNumber: "ABCDE3333F",
            driverLicenseNumber: "DL3333333",
            inviteUser: true,
            role: Role.HR,
            workLocation: getWorkLocationId("Head Office", workLocations),
            department: getDepartmentId("HR", departments),
            designation: getDesignationId("HR Manager", designations),
            tenantId: businessId,
            dateOfBirth: new Date("1989-05-01"),
            dateOfJoining: new Date("2019-01-01"),
            reportingManagerId: null,
            language: "English",
            nationality: "INDIA",
            email: "dave@example.com",
            phoneNumber: "9000000003",
            workEmail: "dave@example.com",
            addressLine1: "789 West St",
            addressLine2: "Apt 10",
            name: "Dave",
            employmentType: EmploymentType.FULL_TIME,
            gender: Gender.MALE,
            maritalStatus: MaritalStatus.SINGLE,
        },
        {
            bankAccountHolderName: "Eve",
            bankAccountNumber: "4444444444",
            bankAccountType: BankAccountType.SAVINGS,
            bankName: "Demo Bank",
            bankBranch: "Main Branch",
            bankIfscCode: "DEMO1234",
            aadhaarNumber: "444444444444",
            panNumber: "ABCDE4444F",
            driverLicenseNumber: "DL4444444",
            inviteUser: true,
            role: Role.EMPLOYEE,
            workLocation: getWorkLocationId("Head Office", workLocations),
            department: getDepartmentId("Engineering", departments),
            designation: getDesignationId("Software Engineer", designations),
            tenantId: businessId,
            dateOfBirth: new Date("1992-03-01"),
            dateOfJoining: new Date("2021-06-01"),
            reportingManagerId: null,
            language: "English",
            nationality: "INDIA",
            email: "eve@example.com",
            phoneNumber: "9000000004",
            workEmail: "eve@example.com",
            addressLine1: "321 East St",
            addressLine2: "Unit 5",
            name: "Eve",
            employmentType: EmploymentType.FULL_TIME,
            gender: Gender.FEMALE,
            maritalStatus: MaritalStatus.SINGLE,
        },
        {
            bankAccountHolderName: "Frank",
            bankAccountNumber: "5555555555",
            bankAccountType: BankAccountType.SAVINGS,
            bankName: "Demo Bank",
            bankBranch: "Main Branch",
            bankIfscCode: "DEMO1234",
            aadhaarNumber: "555555555555",
            panNumber: "ABCDE5555F",
            driverLicenseNumber: "DL5555555",
            inviteUser: true,
            role: Role.EMPLOYEE,
            workLocation: getWorkLocationId("Head Office", workLocations),
            department: getDepartmentId("Engineering", departments),
            designation: getDesignationId("Software Engineer", designations),
            tenantId: businessId,
            dateOfBirth: new Date("1993-04-01"),
            dateOfJoining: new Date("2022-01-01"),
            reportingManagerId: null,
            language: "English",
            nationality: "INDIA",
            email: "frank@example.com",
            phoneNumber: "9000000005",
            workEmail: "frank@example.com",
            addressLine1: "654 South St",
            addressLine2: "Floor 1",
            name: "Frank",
            employmentType: EmploymentType.FULL_TIME,
            gender: Gender.MALE,
            maritalStatus: MaritalStatus.MARRIED,
        },
        {
            bankAccountHolderName: "George",
            bankAccountNumber: "6666666666",
            bankAccountType: BankAccountType.SAVINGS,
            bankName: "Demo Bank",
            bankBranch: "Main Branch",
            bankIfscCode: "DEMO1234",
            aadhaarNumber: "666666666666",
            panNumber: "ABCDE6666F",
            driverLicenseNumber: "DL6666666",
            inviteUser: true,
            role: Role.EMPLOYEE,
            workLocation: getWorkLocationId("Head Office", workLocations),
            department: getDepartmentId("Engineering", departments),
            designation: getDesignationId("Software Engineer", designations),
            tenantId: businessId,
            dateOfBirth: new Date("1994-06-01"),
            dateOfJoining: new Date("2022-03-01"),
            reportingManagerId: null,
            language: "English",
            nationality: "INDIA",
            email: "george@example.com",
            phoneNumber: "9000000006",
            workEmail: "george@example.com",
            addressLine1: "987 North St",
            addressLine2: "Suite 200",
            name: "George",
            employmentType: EmploymentType.FULL_TIME,
            gender: Gender.MALE,
            maritalStatus: MaritalStatus.SINGLE,
        },
        {
            bankAccountHolderName: "Harry",
            bankAccountNumber: "7777777777",
            bankAccountType: BankAccountType.SAVINGS,
            bankName: "Demo Bank",
            bankBranch: "Main Branch",
            bankIfscCode: "DEMO1234",
            aadhaarNumber: "777777777777",
            panNumber: "ABCDE7777F",
            driverLicenseNumber: "DL7777777",
            inviteUser: true,
            role: Role.EMPLOYEE,
            workLocation: getWorkLocationId("Head Office", workLocations),
            department: getDepartmentId("Engineering", departments),
            designation: getDesignationId("Software Engineer", designations),
            tenantId: businessId,
            dateOfBirth: new Date("1995-07-01"),
            dateOfJoining: new Date("2022-04-01"),
            reportingManagerId: null,
            language: "English",
            nationality: "INDIA",
            email: "harry@example.com",
            phoneNumber: "9000000007",
            workEmail: "harry@example.com",
            addressLine1: "111 River Rd",
            addressLine2: "Bldg 5",
            name: "Harry",
            employmentType: EmploymentType.FULL_TIME,
            gender: Gender.MALE,
            maritalStatus: MaritalStatus.SINGLE,
        },
        {
            bankAccountHolderName: "Ian",
            bankAccountNumber: "8888888888",
            bankAccountType: BankAccountType.SAVINGS,
            bankName: "Demo Bank",
            bankBranch: "Main Branch",
            bankIfscCode: "DEMO1234",
            aadhaarNumber: "888888888888",
            panNumber: "ABCDE8888F",
            driverLicenseNumber: "DL8888888",
            inviteUser: true,
            role: Role.EMPLOYEE,
            workLocation: getWorkLocationId("Head Office", workLocations),
            department: getDepartmentId("IT", departments),
            designation: getDesignationId("Junior Software Engineer", designations),
            tenantId: businessId,
            dateOfBirth: new Date("1996-08-01"),
            dateOfJoining: new Date("2022-05-01"),
            reportingManagerId: null,
            language: "English",
            nationality: "INDIA",
            email: "ian@example.com",
            phoneNumber: "9000000008",
            workEmail: "ian@example.com",
            addressLine1: "222 Hill St",
            addressLine2: "Suite 10",
            name: "Ian",
            employmentType: EmploymentType.FULL_TIME,
            gender: Gender.MALE,
            maritalStatus: MaritalStatus.SINGLE,
        },
        {
            bankAccountHolderName: "Joe",
            bankAccountNumber: "9999999999",
            bankAccountType: BankAccountType.SAVINGS,
            bankName: "Demo Bank",
            bankBranch: "Main Branch",
            bankIfscCode: "DEMO1234",
            aadhaarNumber: "999999999999",
            panNumber: "ABCDE9999F",
            driverLicenseNumber: "DL9999999",
            inviteUser: true,
            role: Role.EMPLOYEE,
            workLocation: getWorkLocationId("Head Office", workLocations),
            department: getDepartmentId("Engineering", departments),
            designation: getDesignationId("Software Engineer", designations),
            tenantId: businessId,
            dateOfBirth: new Date("1997-09-01"),
            dateOfJoining: new Date("2022-06-01"),
            reportingManagerId: null,
            language: "English",
            nationality: "INDIA",
            email: "joe@example.com",
            phoneNumber: "9000000009",
            workEmail: "joe@example.com",
            addressLine1: "333 Market St",
            addressLine2: "Suite 20",
            name: "Joe",
            employmentType: EmploymentType.FULL_TIME,
            gender: Gender.MALE,
            maritalStatus: MaritalStatus.SINGLE,
        },
        {
            bankAccountHolderName: "Kevin",
            bankAccountNumber: "1010101010",
            bankAccountType: BankAccountType.SAVINGS,
            bankName: "Demo Bank",
            bankBranch: "Main Branch",
            bankIfscCode: "DEMO1234",
            aadhaarNumber: "101010101010",
            panNumber: "ABCDE1010F",
            driverLicenseNumber: "DL10101010",
            inviteUser: true,
            role: Role.EMPLOYEE,
            workLocation: getWorkLocationId("Head Office", workLocations),
            department: getDepartmentId("Engineering", departments),
            designation: getDesignationId("Software Engineer", designations),
            tenantId: businessId,
            dateOfBirth: new Date("1998-10-01"),
            dateOfJoining: new Date("2022-07-01"),
            reportingManagerId: null,
            language: "English",
            nationality: "INDIA",
            email: "kevin@example.com",
            phoneNumber: "9000000010",
            workEmail: "kevin@example.com",
            addressLine1: "444 Park St",
            addressLine2: "Suite 30",
            name: "Kevin",
            employmentType: EmploymentType.FULL_TIME,
            gender: Gender.MALE,
            maritalStatus: MaritalStatus.SINGLE,
        },
        {
            bankAccountHolderName: "Lisa",
            bankAccountNumber: "1212121212",
            bankAccountType: BankAccountType.SAVINGS,
            bankName: "Demo Bank",
            bankBranch: "Main Branch",
            bankIfscCode: "DEMO1234",
            aadhaarNumber: "121212121212",
            panNumber: "ABCDE1212F",
            driverLicenseNumber: "DL12121212",
            inviteUser: true,
            role: Role.EMPLOYEE,
            workLocation: getWorkLocationId("Head Office", workLocations),
            department: getDepartmentId("Sales", departments),
            designation: getDesignationId("Sales Manager", designations),
            tenantId: businessId,
            dateOfBirth: new Date("1999-11-01"),
            dateOfJoining: new Date("2022-08-01"),
            reportingManagerId: null,
            language: "English",
            nationality: "INDIA",
            email: "lisa@example.com",
            phoneNumber: "9000000011",
            workEmail: "lisa@example.com",
            addressLine1: "555 Pine St",
            addressLine2: "Suite 40",
            name: "Lisa",
            employmentType: EmploymentType.FULL_TIME,
            gender: Gender.FEMALE,
            maritalStatus: MaritalStatus.SINGLE,
        },
    ]

}

export const departmentsData: DepartmentData[] = [
    {
        name: 'Sales',
        code: 'SA',
        description: 'Sales department',
        tenantId: businessId,
        createdAt: getDateMonthsAgo(5),
    },
    {
        name: 'Marketing',
        code: 'MA',
        description: 'Marketing department',
        tenantId: businessId,
    },
    {
        name: 'Engineering',
        code: 'EN',
        description: 'Engineering department',
        tenantId: businessId,
        createdAt: getDateMonthsAgo(8),
    },
    {
        name: 'HR',
        code: 'HR',
        description: 'HR department',
        tenantId: businessId,
    },
    {
        name: 'Finance',
        code: 'FI',
        description: 'Finance department',
        tenantId: businessId,
    },
    {
        name: 'Legal',
        code: 'LE',
        description: 'Legal department',
        tenantId: businessId,
        createdAt: getDateMonthsAgo(10),
    },
    {
        name: 'IT',
        code: 'IT',
        description: 'IT department',
        tenantId: businessId,
    },
]

export const designationsData: DesignationData[] = [
    {
        name: "CTO",
        tenantId: businessId,
    },
    {
        name: "CFO",
        tenantId: businessId,
    },
    {
        name: "CMO",
        tenantId: businessId,
    },
    {
        name: "Software Engineer",
        tenantId: businessId,
    },
    {
        name: "Junior Software Engineer",
        tenantId: businessId,
    },
    {
        name: "HR Manager",
        tenantId: businessId,
    },
    {
        name: "Sales Manager",
        tenantId: businessId,
    },
    {
        name: "Marketing Manager",
        tenantId: businessId,
    },
    {
        name: "Finance Manager",
        tenantId: businessId,
    },
    {
        name: "Designer",
        tenantId: businessId,
    },

]

export const workLocationsData: WorkLocationData[] = [
    {
        name: 'Head Office',
        tenantId: businessId,
        state: 'Maharashtra',
        city: 'Pune',
        pincode: '411001',
        addressLine1: 'Pune',
        addressLine2: 'Pune',
    },
    {
        name: 'Regional Office',
        tenantId: businessId,
        state: 'Karnataka',
        city: 'Bengaluru',
        pincode: '560001',
        addressLine1: 'MG Road',
        addressLine2: 'Bengaluru',
    },
    {
        name: 'Branch Office',
        tenantId: businessId,
        state: 'Delhi',
        city: 'New Delhi',
        pincode: '110001',
        addressLine1: 'Connaught Place',
        addressLine2: 'New Delhi',
    },
    {
        name: 'Sales Office',
        tenantId: businessId,
        state: 'Tamil Nadu',
        city: 'Chennai',
        pincode: '600001',
        addressLine1: 'T Nagar',
        addressLine2: 'Chennai',
    },
    {
        name: 'Support Office',
        tenantId: businessId,
        state: 'West Bengal',
        city: 'Kolkata',
        pincode: '700001',
        addressLine1: 'Park Street',
        addressLine2: 'Kolkata',
    },
    {
        name: 'R&D Center',
        tenantId: businessId,
        state: 'Telangana',
        city: 'Hyderabad',
        pincode: '500001',
        addressLine1: 'Hitech City',
        addressLine2: 'Hyderabad',
    },
    {
        name: 'Finance Office',
        tenantId: businessId,
        state: 'Gujarat',
        city: 'Ahmedabad',
        pincode: '380001',
        addressLine1: 'Ashram Road',
        addressLine2: 'Ahmedabad',
    },
    {
        name: 'Marketing Office',
        tenantId: businessId,
        state: 'Maharashtra',
        city: 'Mumbai',
        pincode: '400001',
        addressLine1: 'Nariman Point',
        addressLine2: 'Mumbai',
    },
]

export const invitesData = [
    {
        email: 'alice@example.com',
        tenantId: businessId,
        role: Role.MANAGER,
        status: InviteStatus.PENDING,
        emailSent: true,
        invitedBy: userId,
        name: 'Alice',
    },
    {
        email: 'bob@example.com',
        tenantId: businessId,
        role: Role.EMPLOYEE,
        status: InviteStatus.DECLINED,
        emailSent: true,
        invitedBy: userId,
        name: 'Bob',
    },
    {
        email: 'charlie@example.com',
        tenantId: businessId,
        role: Role.STAKEHOLDER,
        status: InviteStatus.PENDING,
        emailSent: true,
        invitedBy: userId,
        name: 'Charlie',
    },
    {
        email: 'dave@example.com',
        tenantId: businessId,
        role: Role.HR,
        status: InviteStatus.PENDING,
        emailSent: true,
        invitedBy: userId,
        name: 'Dave',
    },
    {
        email: 'eve@example.com',
        tenantId: businessId,
        role: Role.EMPLOYEE,
        status: InviteStatus.PENDING,
        emailSent: true,
        invitedBy: userId,
        name: 'Eve',
    },
    {
        email: 'frank@example.com',
        tenantId: businessId,
        role: Role.EMPLOYEE,
        status: InviteStatus.EXPIRED,
        emailSent: true,
        invitedBy: userId,
        name: 'Frank',
    },
    {
        email: 'george@example.com',
        tenantId: businessId,
        role: Role.EMPLOYEE,
        status: InviteStatus.PENDING,
        emailSent: true,
        invitedBy: userId,
        name: 'George',
    },
    {
        email: 'harry@example.com',
        tenantId: businessId,
        role: Role.EMPLOYEE,
        status: InviteStatus.DECLINED,
        emailSent: true,
        invitedBy: userId,
        name: 'Harry',
    },
    {
        email: 'ian@example.com',
        tenantId: businessId,
        role: Role.EMPLOYEE,
        status: InviteStatus.PENDING,
        emailSent: false,
        invitedBy: userId,
        name: 'Ian',
    },
    {
        email: 'joe@example.com',
        tenantId: businessId,
        role: Role.EMPLOYEE,
        status: InviteStatus.PENDING,
        emailSent: false,
        invitedBy: userId,
        name: 'Joe',
    },
    {
        email: 'kevin@example.com',
        tenantId: businessId,
        role: Role.EMPLOYEE,
        status: InviteStatus.PENDING,
        emailSent: false,
        invitedBy: userId,
        name: 'Kevin',
    },
    {
        email: 'lisa@example.com',
        tenantId: businessId,
        role: Role.EMPLOYEE,
        status: InviteStatus.PENDING,
        emailSent: false,
        invitedBy: userId,
        name: 'Lisa',
    },
] 
